{"uid":"aea76afdb65a9b5b","name":"hsmAPIinventoryHardwareDisruptive","fullName":"api.2-disruptive.test_hardware.tavern#hsmAPIinventoryHardwareDisruptive","historyId":"835ff18518ce742b155f9cf4039900b3","time":{"start":1711009136329,"stop":1711009138597,"duration":2268},"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fa35b2ade50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/484'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/486'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/492'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/500'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","statusTrace":"Format variables:\n  hsm_base_url = 'http://cray-smd:27779'\n  verify = 'False'\n\nSource test stage (line 2205):\n  - name: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.\n    request:\n      url: \"{hsm_base_url}/hsm/v2/Inventory/Hardware\"\n      method: GET\n      verify: !bool \"{verify}\"\n    response:\n      status_code: 200\n      verify_response_with:\n        function: tavern.testutils.helpers:validate_pykwalify\n        extra_kwargs:\n          schema:\n            type: seq\n            required: True\n            matching: all\n            sequence:\n              - type: map\n                required: True\n\n                allowempty: True\n                mapping:\n                  ID:\n                    type: str\n                    required: True\n                  Type:\n                    type: str\n                    required: True\n                  Ordinal:\n                    type: int\n                    required: True\n                  Status:\n                    type: str\n                    required: True\n                  HWInventoryByLocationType:\n                    type: str\n                    required: True\n                  PopulatedFRU:\n                    type: map\n                    required: True\n\n                    allowempty: True\n                    mapping:\n                      FRUID:\n                        type: str\n                        required: True\n                      Type:\n                        type: str\n                        required: True\n                      Subtype:\n                        type: str\n                        required: True\n\n\n\n\nFormatted stage:\n  name: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using\n    GET.\n  request:\n    method: GET\n    url: 'http://cray-smd:27779/hsm/v2/Inventory/Hardware'\n    verify: !bool 'False'\n  response:\n    status_code: 200\n    verify_response_with:\n      extra_kwargs:\n        schema:\n          matching: all\n          required: true\n          sequence:\n          - allowempty: true\n            mapping:\n              HWInventoryByLocationType:\n                required: true\n                type: str\n              ID:\n                required: true\n                type: str\n              Ordinal:\n                required: true\n                type: int\n              PopulatedFRU:\n                allowempty: true\n                mapping:\n                  FRUID:\n                    required: true\n                    type: str\n                  Subtype:\n                    required: true\n                    type: str\n                  Type:\n                    required: true\n                    type: str\n                required: true\n                type: map\n              Status:\n                required: true\n                type: str\n              Type:\n                required: true\n                type: str\n            required: true\n            type: map\n          type: seq\n      function: tavern.testutils.helpers:validate_pykwalify\n\nErrors:\nE   tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n    - Error calling validate function '<function validate_pykwalify at 0x7fa35b2ade50>':\n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n            verifier.validate()\n          File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n            raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n        pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n         - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/484'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/486'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/492'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/500'.: Path: '/'>\n    \n        The above exception was the direct cause of the following exception:\n    \n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n            vf(response)\n          File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n            result = func(response, *args, **kwargs)\n          File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n            verify_generic(to_verify, schema)\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n            raise BadSchemaError() from e\n        tavern.util.exceptions.BadSchemaError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fa35b2ade50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/484'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/486'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/492'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/500'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","statusTrace":"Format variables:\n  hsm_base_url = 'http://cray-smd:27779'\n  verify = 'False'\n\nSource test stage (line 2205):\n  - name: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.\n    request:\n      url: \"{hsm_base_url}/hsm/v2/Inventory/Hardware\"\n      method: GET\n      verify: !bool \"{verify}\"\n    response:\n      status_code: 200\n      verify_response_with:\n        function: tavern.testutils.helpers:validate_pykwalify\n        extra_kwargs:\n          schema:\n            type: seq\n            required: True\n            matching: all\n            sequence:\n              - type: map\n                required: True\n\n                allowempty: True\n                mapping:\n                  ID:\n                    type: str\n                    required: True\n                  Type:\n                    type: str\n                    required: True\n                  Ordinal:\n                    type: int\n                    required: True\n                  Status:\n                    type: str\n                    required: True\n                  HWInventoryByLocationType:\n                    type: str\n                    required: True\n                  PopulatedFRU:\n                    type: map\n                    required: True\n\n                    allowempty: True\n                    mapping:\n                      FRUID:\n                        type: str\n                        required: True\n                      Type:\n                        type: str\n                        required: True\n                      Subtype:\n                        type: str\n                        required: True\n\n\n\n\nFormatted stage:\n  name: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using\n    GET.\n  request:\n    method: GET\n    url: 'http://cray-smd:27779/hsm/v2/Inventory/Hardware'\n    verify: !bool 'False'\n  response:\n    status_code: 200\n    verify_response_with:\n      extra_kwargs:\n        schema:\n          matching: all\n          required: true\n          sequence:\n          - allowempty: true\n            mapping:\n              HWInventoryByLocationType:\n                required: true\n                type: str\n              ID:\n                required: true\n                type: str\n              Ordinal:\n                required: true\n                type: int\n              PopulatedFRU:\n                allowempty: true\n                mapping:\n                  FRUID:\n                    required: true\n                    type: str\n                  Subtype:\n                    required: true\n                    type: str\n                  Type:\n                    required: true\n                    type: str\n                required: true\n                type: map\n              Status:\n                required: true\n                type: str\n              Type:\n                required: true\n                type: str\n            required: true\n            type: map\n          type: seq\n      function: tavern.testutils.helpers:validate_pykwalify\n\nErrors:\nE   tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n    - Error calling validate function '<function validate_pykwalify at 0x7fa35b2ade50>':\n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n            verifier.validate()\n          File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n            raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n        pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n         - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/484'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/486'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/492'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/500'.: Path: '/'>\n    \n        The above exception was the direct cause of the following exception:\n    \n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n            vf(response)\n          File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n            result = func(response, *args, **kwargs)\n          File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n            verify_generic(to_verify, schema)\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n            raise BadSchemaError() from e\n        tavern.util.exceptions.BadSchemaError","steps":[{"name":"Stage 0: hsmAPIinventoryHardwarePOSTcmmRectifier - Create a CMMRectifier Hardware Inventory entry using POST.","time":{"start":1711009136352,"stop":1711009136367,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"64337823d94be47","name":"stage_yaml","source":"64337823d94be47.yaml","type":"application/yaml","size":1257},{"uid":"2da8423f3be625a7","name":"rest_request","source":"2da8423f3be625a7.yaml","type":"application/yaml","size":779},{"uid":"2729c688d809625c","name":"rest_response","source":"2729c688d809625c.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: hsmAPIinventoryHardwareXnameGETcmmRectifier - Retrieve a CMMRectifier Hardware Inventory entry by xname using GET.","time":{"start":1711009136367,"stop":1711009136380,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"b97d51ec214e9353","name":"stage_yaml","source":"b97d51ec214e9353.yaml","type":"application/yaml","size":3659},{"uid":"3fd4e4f9e63d8a5b","name":"rest_request","source":"3fd4e4f9e63d8a5b.yaml","type":"application/yaml","size":138},{"uid":"5d5ddd7007b6f28f","name":"rest_response","source":"5d5ddd7007b6f28f.yaml","type":"application/yaml","size":741}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 2: hsmAPIinventoryHardwarePOSTchassis - Create a Chassis Hardware Inventory entry using POST.","time":{"start":1711009136381,"stop":1711009136394,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"39a6a9441b9e0141","name":"stage_yaml","source":"39a6a9441b9e0141.yaml","type":"application/yaml","size":1204},{"uid":"86d1afa8a0efe78d","name":"rest_request","source":"86d1afa8a0efe78d.yaml","type":"application/yaml","size":731},{"uid":"6d80a5a5d0402fe2","name":"rest_response","source":"6d80a5a5d0402fe2.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 3: hsmAPIinventoryHardwareXnameGETchassis - Retrieve a Chassis Hardware Inventory entry by xname using GET.","time":{"start":1711009136394,"stop":1711009136407,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"7ced7015c9a1aa6c","name":"stage_yaml","source":"7ced7015c9a1aa6c.yaml","type":"application/yaml","size":3706},{"uid":"f6984c38d6aeefa7","name":"rest_request","source":"f6984c38d6aeefa7.yaml","type":"application/yaml","size":136},{"uid":"2ef13942a7a373f0","name":"rest_response","source":"2ef13942a7a373f0.yaml","type":"application/yaml","size":691}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 4: hsmAPIinventoryHardwarePOSTcomputeModule - Create a ComputeModule Hardware Inventory entry using POST.","time":{"start":1711009136408,"stop":1711009136421,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"47f6086e880560f","name":"stage_yaml","source":"47f6086e880560f.yaml","type":"application/yaml","size":1201},{"uid":"b4354e1d8fb5213e","name":"rest_request","source":"b4354e1d8fb5213e.yaml","type":"application/yaml","size":722},{"uid":"629592ef69ef4585","name":"rest_response","source":"629592ef69ef4585.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 5: hsmAPIinventoryHardwareXnameGETcomputeModule - Retrieve a ComputeModule Hardware Inventory entry by xname using GET.","time":{"start":1711009136421,"stop":1711009136434,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"cddd5fd1d75133e","name":"stage_yaml","source":"cddd5fd1d75133e.yaml","type":"application/yaml","size":3705},{"uid":"be565c198fb7c5b8","name":"rest_request","source":"be565c198fb7c5b8.yaml","type":"application/yaml","size":138},{"uid":"5ec8de0aef3df198","name":"rest_response","source":"5ec8de0aef3df198.yaml","type":"application/yaml","size":682}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 6: hsmAPIinventoryHardwarePOSThsnBoard - Create an HSNBoard Hardware Inventory entry using POST.","time":{"start":1711009136435,"stop":1711009136448,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"310cdbcf9157e3ae","name":"stage_yaml","source":"310cdbcf9157e3ae.yaml","type":"application/yaml","size":1268},{"uid":"3aa0f8230e2b92f5","name":"rest_request","source":"3aa0f8230e2b92f5.yaml","type":"application/yaml","size":792},{"uid":"decbd8c98dd50bc7","name":"rest_response","source":"decbd8c98dd50bc7.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 7: hsmAPIinventoryHardwareXnameGEThsnBoard - Retrieve an HSNBoard Hardware Inventory entry by xname using GET.","time":{"start":1711009136449,"stop":1711009136462,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"20406c7aa24aa6c1","name":"stage_yaml","source":"20406c7aa24aa6c1.yaml","type":"application/yaml","size":3774},{"uid":"6895a6dbdc45c1cb","name":"rest_request","source":"6895a6dbdc45c1cb.yaml","type":"application/yaml","size":140},{"uid":"e388a5375807469d","name":"rest_response","source":"e388a5375807469d.yaml","type":"application/yaml","size":752}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 8: hsmAPIinventoryHardwarePOSTmemory - Create a Memory Hardware Inventory entry using POST.","time":{"start":1711009136462,"stop":1711009136477,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"a6a63cd2792a1de","name":"stage_yaml","source":"a6a63cd2792a1de.yaml","type":"application/yaml","size":1405},{"uid":"ba49d060b14cbdef","name":"rest_request","source":"ba49d060b14cbdef.yaml","type":"application/yaml","size":993},{"uid":"b7f4a46abdfa58e7","name":"rest_response","source":"b7f4a46abdfa58e7.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 9: hsmAPIinventoryHardwareXnameGETmemory - Retrieve a Memory Hardware Inventory entry by xname using GET.","time":{"start":1711009136477,"stop":1711009136492,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"f7d8ce050df0e574","name":"stage_yaml","source":"f7d8ce050df0e574.yaml","type":"application/yaml","size":5172},{"uid":"157db4b1fc08859f","name":"rest_request","source":"157db4b1fc08859f.yaml","type":"application/yaml","size":144},{"uid":"e100ee4bc2bccd10","name":"rest_response","source":"e100ee4bc2bccd10.yaml","type":"application/yaml","size":935}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 10: hsmAPIinventoryHardwarePOSTnodeBMC - Create a NodeBMC Hardware Inventory entry using POST.","time":{"start":1711009136492,"stop":1711009136508,"duration":16},"status":"passed","steps":[],"attachments":[{"uid":"7d269c1281a16c36","name":"stage_yaml","source":"7d269c1281a16c36.yaml","type":"application/yaml","size":1220},{"uid":"de440af891f78d3e","name":"rest_request","source":"de440af891f78d3e.yaml","type":"application/yaml","size":749},{"uid":"8e685dc8e0b09605","name":"rest_response","source":"8e685dc8e0b09605.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 11: hsmAPIinventoryHardwareXnameGETnodeBMC - Retrieve a NodeBMC Hardware Inventory entry by xname using GET.","time":{"start":1711009136508,"stop":1711009136523,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"a717c8099b91462d","name":"stage_yaml","source":"a717c8099b91462d.yaml","type":"application/yaml","size":3686},{"uid":"86258b622a1f261e","name":"rest_request","source":"86258b622a1f261e.yaml","type":"application/yaml","size":140},{"uid":"584aba4f540584b1","name":"rest_response","source":"584aba4f540584b1.yaml","type":"application/yaml","size":709}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 12: hsmAPIinventoryHardwarePOSTnodeEnclosure - Create a NodeEnclosure Hardware Inventory entry using POST.","time":{"start":1711009136524,"stop":1711009136538,"duration":14},"status":"passed","steps":[],"attachments":[{"uid":"7e4bd7ad205cdd15","name":"stage_yaml","source":"7e4bd7ad205cdd15.yaml","type":"application/yaml","size":1262},{"uid":"f4aee41c4ff609c4","name":"rest_request","source":"f4aee41c4ff609c4.yaml","type":"application/yaml","size":777},{"uid":"db8526a899c09a32","name":"rest_response","source":"db8526a899c09a32.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 13: hsmAPIinventoryHardwareXnameGETnodeEnclosure - Retrieve a NodeEnclosure Hardware Inventory entry by xname using GET.","time":{"start":1711009136539,"stop":1711009136552,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"22e7dcf3ef8ceddc","name":"stage_yaml","source":"22e7dcf3ef8ceddc.yaml","type":"application/yaml","size":3768},{"uid":"3e0cadc456031e60","name":"rest_request","source":"3e0cadc456031e60.yaml","type":"application/yaml","size":140},{"uid":"6216274fe1d0ba55","name":"rest_response","source":"6216274fe1d0ba55.yaml","type":"application/yaml","size":737}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 14: hsmAPIinventoryHardwarePOSTnodeHsnNic - Create a NodeHsnNic Hardware Inventory entry using POST.","time":{"start":1711009136552,"stop":1711009136566,"duration":14},"status":"passed","steps":[],"attachments":[{"uid":"306c09a2be82e98f","name":"stage_yaml","source":"306c09a2be82e98f.yaml","type":"application/yaml","size":1198},{"uid":"1dca255c102d5a7e","name":"rest_request","source":"1dca255c102d5a7e.yaml","type":"application/yaml","size":697},{"uid":"520b4a4187e68db6","name":"rest_response","source":"520b4a4187e68db6.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 15: hsmAPIinventoryHardwareXnameGETnodeHsnNic - Retrieve a NodeHsnNic Hardware Inventory entry by xname using GET.","time":{"start":1711009136566,"stop":1711009136579,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"553652fd9bc756c7","name":"stage_yaml","source":"553652fd9bc756c7.yaml","type":"application/yaml","size":3160},{"uid":"80962368f9a238b1","name":"rest_request","source":"80962368f9a238b1.yaml","type":"application/yaml","size":144},{"uid":"2838872cf413b28a","name":"rest_response","source":"2838872cf413b28a.yaml","type":"application/yaml","size":665}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 16: hsmAPIinventoryHardwarePOSTnodeCreate - Create a Node Hardware Inventory entry using POST.","time":{"start":1711009136580,"stop":1711009136595,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"b0fe3f00b46fdda7","name":"stage_yaml","source":"b0fe3f00b46fdda7.yaml","type":"application/yaml","size":1354},{"uid":"14036d81c0ff2d05","name":"rest_request","source":"14036d81c0ff2d05.yaml","type":"application/yaml","size":918},{"uid":"262f3fdb73cbbaec","name":"rest_response","source":"262f3fdb73cbbaec.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 17: hsmAPIinventoryHardwareXnameGETnodeCreate - Retrieve a Node Hardware Inventory entry by xname using GET.","time":{"start":1711009136595,"stop":1711009136609,"duration":14},"status":"passed","steps":[],"attachments":[{"uid":"f56f60ffa6fff6e8","name":"stage_yaml","source":"f56f60ffa6fff6e8.yaml","type":"application/yaml","size":4772},{"uid":"64e8ad594f5ff9fb","name":"rest_request","source":"64e8ad594f5ff9fb.yaml","type":"application/yaml","size":142},{"uid":"8964c08d3afb89a6","name":"rest_response","source":"8964c08d3afb89a6.yaml","type":"application/yaml","size":862}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 18: hsmAPIinventoryHardwarePOSTnodeUpdate - Update a Node Hardware Inventory entry using POST.","time":{"start":1711009136610,"stop":1711009136623,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"2516f78e691e1de6","name":"stage_yaml","source":"2516f78e691e1de6.yaml","type":"application/yaml","size":1393},{"uid":"22717483445d4341","name":"rest_request","source":"22717483445d4341.yaml","type":"application/yaml","size":953},{"uid":"3e1968c12b0d7cd9","name":"rest_response","source":"3e1968c12b0d7cd9.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 19: hsmAPIinventoryHardwareXnameGETnodeUpdate - Retrieve an updated Node Hardware Inventory entry by xname using GET.","time":{"start":1711009136623,"stop":1711009136638,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"87c033928952ac69","name":"stage_yaml","source":"87c033928952ac69.yaml","type":"application/yaml","size":4820},{"uid":"2037678b53f4c0d3","name":"rest_request","source":"2037678b53f4c0d3.yaml","type":"application/yaml","size":142},{"uid":"2662a89901fadc49","name":"rest_response","source":"2662a89901fadc49.yaml","type":"application/yaml","size":897}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 20: hsmAPIinventoryHardwarePOSTprocessor - Create a Processor Hardware Inventory entry using POST.","time":{"start":1711009136638,"stop":1711009136653,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"6f1c59c1d1e4d04e","name":"stage_yaml","source":"6f1c59c1d1e4d04e.yaml","type":"application/yaml","size":1505},{"uid":"8050be3ad9c8bb53","name":"rest_request","source":"8050be3ad9c8bb53.yaml","type":"application/yaml","size":1115},{"uid":"5fbdd715ee1d8c03","name":"rest_response","source":"5fbdd715ee1d8c03.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 21: hsmAPIinventoryHardwareXnameGETprocessor - Retrieve a Processor Hardware Inventory entry by xname using GET.","time":{"start":1711009136654,"stop":1711009136669,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"be46e3f38173b328","name":"stage_yaml","source":"be46e3f38173b328.yaml","type":"application/yaml","size":5555},{"uid":"641d6adf338d8337","name":"rest_request","source":"641d6adf338d8337.yaml","type":"application/yaml","size":144},{"uid":"10c5fdb48fb489f","name":"rest_response","source":"10c5fdb48fb489f.yaml","type":"application/yaml","size":1053}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 22: hsmAPIinventoryHardwarePOSTrouterBMC - Create a RouterBMC Hardware Inventory entry using POST.","time":{"start":1711009136669,"stop":1711009136683,"duration":14},"status":"passed","steps":[],"attachments":[{"uid":"914c8029f67dbbb6","name":"stage_yaml","source":"914c8029f67dbbb6.yaml","type":"application/yaml","size":1226},{"uid":"6de2606ae3142264","name":"rest_request","source":"6de2606ae3142264.yaml","type":"application/yaml","size":753},{"uid":"b48b07126b6f6e4d","name":"rest_response","source":"b48b07126b6f6e4d.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 23: hsmAPIinventoryHardwareXnameGETrouterBMC - Retrieve a RouterBMC Hardware Inventory entry by xname using GET.","time":{"start":1711009136683,"stop":1711009136692,"duration":9},"status":"passed","steps":[],"attachments":[{"uid":"870ae0cb43cdc66b","name":"stage_yaml","source":"870ae0cb43cdc66b.yaml","type":"application/yaml","size":272},{"uid":"1714eb17ef05db72","name":"rest_request","source":"1714eb17ef05db72.yaml","type":"application/yaml","size":140},{"uid":"cfe7ce073679d55d","name":"rest_response","source":"cfe7ce073679d55d.yaml","type":"application/yaml","size":713}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 24: hsmAPIinventoryHardwarePOSTrouterModule - Create a RouterModule Hardware Inventory entry using POST.","time":{"start":1711009136692,"stop":1711009136706,"duration":14},"status":"passed","steps":[],"attachments":[{"uid":"85d583a975794679","name":"stage_yaml","source":"85d583a975794679.yaml","type":"application/yaml","size":1193},{"uid":"f075b63417ed5459","name":"rest_request","source":"f075b63417ed5459.yaml","type":"application/yaml","size":716},{"uid":"e35316b2e6de4961","name":"rest_response","source":"e35316b2e6de4961.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 25: hsmAPIinventoryHardwareXnameGETrouterModule - Retrieve a RouterModule Hardware Inventory entry by xname using GET.","time":{"start":1711009136706,"stop":1711009136719,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"17db68909efc9528","name":"stage_yaml","source":"17db68909efc9528.yaml","type":"application/yaml","size":3697},{"uid":"204abd0e263d6aa3","name":"rest_request","source":"204abd0e263d6aa3.yaml","type":"application/yaml","size":138},{"uid":"295e547635c91d0e","name":"rest_response","source":"295e547635c91d0e.yaml","type":"application/yaml","size":676}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 26: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.","time":{"start":1711009136719,"stop":1711009138596,"duration":1877},"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fa35b2ade50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/484'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/486'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/492'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/500'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError\n\n","statusTrace":"  File \"/usr/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/usr/lib/python3.9/site-packages/tavern/util/retry.py\", line 31, in wrapped\n    res = fn(*args, **kwargs)\n  File \"/usr/lib/python3.9/site-packages/tavern/core.py\", line 270, in run_stage\n    saved = v.verify(response)\n  File \"/usr/lib/python3.9/site-packages/tavern/_plugins/rest/response.py\", line 201, in verify\n    raise exceptions.TestFailError(\n","steps":[],"attachments":[{"uid":"8d3d4712842effc9","name":"stage_yaml","source":"8d3d4712842effc9.yaml","type":"application/yaml","size":1437},{"uid":"d92f74e7af2eff3e","name":"rest_request","source":"d92f74e7af2eff3e.yaml","type":"application/yaml","size":128},{"uid":"263fc8892b8819a8","name":"rest_response","source":"263fc8892b8819a8.yaml","type":"application/yaml","size":579275}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[{"uid":"8ff94efaf7871ecd","name":"error_output","source":"8ff94efaf7871ecd.attach","type":"text/plain","size":6715},{"uid":"d705b4971b9a36aa","name":"log","source":"d705b4971b9a36aa.txt","type":"text/plain","size":582667}],"parameters":[],"stepsCount":27,"attachmentsCount":83,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-smd-hmth-test"},{"name":"suite","value":"disruptive"},{"name":"host","value":"00f339fbf78c"},{"name":"thread","value":"9-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.2-disruptive.test_hardware.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":363,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":363},"items":[{"uid":"60ca966767f710ac","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f959a05be50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/27'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/406'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/417'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/421'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/422'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710922762532,"stop":1710922764798,"duration":2266}},{"uid":"6353e25add376159","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7e8f30a53e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/418'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/422'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/434'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/435'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710836940893,"stop":1710836943142,"duration":2249}},{"uid":"72df651a5bbbfc29","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f0a58a6ae50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/503'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/507'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/508'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/509'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710750611175,"stop":1710750613498,"duration":2323}},{"uid":"2d482e730c6a9da8","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7602a8840e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/541'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/550'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/553'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/554'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710663994951,"stop":1710663997261,"duration":2310}},{"uid":"bca98c85d95a1c73","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x79047850ee50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/74'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/418'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/422'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/427'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/436'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710577735814,"stop":1710577738051,"duration":2237}},{"uid":"a442734c7a45be32","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7580d6a91e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/307'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/575'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/577'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710491331165,"stop":1710491333439,"duration":2274}},{"uid":"1d325bb6c5e9d7ab","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7e206888be50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/613'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/617'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/620'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/622'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710404849994,"stop":1710404852278,"duration":2284}},{"uid":"88f94afcde03191f","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x784e6140ae50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/27'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/434'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/444'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/469'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/471'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710317884587,"stop":1710317886830,"duration":2243}},{"uid":"827bc393397cd88a","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f2fed262e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/77'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/78'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/81'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/86'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710231473794,"stop":1710231476166,"duration":2372}},{"uid":"853244bb0dc182cc","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fb5fc177e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/256'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/302'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/628'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/633'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710145097716,"stop":1710145099933,"duration":2217}},{"uid":"11de06d26ac4caca","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f6b0855ae50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/322'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/323'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/324'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/332'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710058675402,"stop":1710058677671,"duration":2269}},{"uid":"baf318d63f236b52","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fb7e6c88e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/273'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/279'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/288'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/289'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709972249091,"stop":1709972251299,"duration":2208}},{"uid":"dc03e0d648215767","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f7176348e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/490'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/493'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/502'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/507'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709885879644,"stop":1709885881939,"duration":2295}},{"uid":"9a299cf2749c5bf5","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fad60701e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/326'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/335'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/336'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/343'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709799462456,"stop":1709799464736,"duration":2280}},{"uid":"ab682c6e6cf3c83c","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fd53be66e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/27'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/749'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/759'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/762'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/768'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709712587774,"stop":1709712590052,"duration":2278}},{"uid":"31105e23934ba537","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f74fc0c1e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/27'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/738'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/743'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/744'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/752'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709626136277,"stop":1709626138527,"duration":2250}},{"uid":"fb912fec0d5df0d7","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fb35c0b5e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/27'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/484'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/492'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/495'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/500'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709540484956,"stop":1709540487289,"duration":2333}},{"uid":"c34c53e0a26027b","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f784d7e5e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/297'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/298'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/306'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/308'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709453387610,"stop":1709453389952,"duration":2342}},{"uid":"87cc528b1841d6bd","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fddb8cf5e50>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/423'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/424'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/426'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/430'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709366925534,"stop":1709366927897,"duration":2363}},{"uid":"808da2dfe8176e61","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f7eb7a17d30>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/27'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/500'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/757'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/760'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/763'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709280527525,"stop":1709280529767,"duration":2242}}]},"tags":[]},"source":"aea76afdb65a9b5b.json","parameterValues":[]}