{"uid":"700568e6ef51be5c","name":"capmcAPIxnameOnPOSTonComputeNode - Verify xname_on keeps power on for a compute node that is already powered on","fullName":"api.2-disruptive.test_xname_on.tavern#capmcAPIxnameOnPOSTonComputeNode - Verify xname_on keeps power on for a compute node that is already powered on","historyId":"97a360bc5658978b69418312f184c4f0","time":{"start":1678224327139,"stop":1678224333267,"duration":6128},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"passed","steps":[{"name":"Stage 0: capmcAPIxnameOnPOSTonComputeNodeTarget - Retrieve a compute node from HSM to be used in later stages","time":{"start":1678224327148,"stop":1678224327184,"duration":36},"status":"passed","steps":[],"attachments":[{"uid":"dc1b5c3f63cd611b","name":"stage_yaml","source":"dc1b5c3f63cd611b.yaml","type":"application/yaml","size":343},{"uid":"42ae54e43b19716b","name":"rest_request","source":"42ae54e43b19716b.yaml","type":"application/yaml","size":162},{"uid":"5e1958923f71ea8b","name":"rest_response","source":"5e1958923f71ea8b.yaml","type":"application/yaml","size":5773}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: capmcAPIxnameOnPOSTonComputeNodePrep - Power the target node on to prepare it for the test case","time":{"start":1678224327185,"stop":1678224329207,"duration":2022},"status":"passed","steps":[],"attachments":[{"uid":"56a1bb19ced68dad","name":"stage_yaml","source":"56a1bb19ced68dad.yaml","type":"application/yaml","size":786},{"uid":"2d1e718b8e36cd20","name":"rest_request","source":"2d1e718b8e36cd20.yaml","type":"application/yaml","size":254},{"uid":"bbae524ec927a1a4","name":"rest_response","source":"bbae524ec927a1a4.yaml","type":"application/yaml","size":173}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 2: capmcAPIxnameOnPOSTonComputeNodeStatusCheck - Verify that the target node is powered on using get_xname_status","time":{"start":1678224329208,"stop":1678224330226,"duration":1018},"status":"passed","steps":[],"attachments":[{"uid":"dc9354e571aebe58","name":"stage_yaml","source":"dc9354e571aebe58.yaml","type":"application/yaml","size":1077},{"uid":"72b6b034dbdaecae","name":"rest_request","source":"72b6b034dbdaecae.yaml","type":"application/yaml","size":183},{"uid":"9f60819253609653","name":"rest_response","source":"9f60819253609653.yaml","type":"application/yaml","size":199}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 3: capmcAPIxnameOnPOSTonComputeNodeActual - Power the target node on using xname_on","time":{"start":1678224330226,"stop":1678224332248,"duration":2022},"status":"passed","steps":[],"attachments":[{"uid":"40c035ca4899bb2b","name":"stage_yaml","source":"40c035ca4899bb2b.yaml","type":"application/yaml","size":773},{"uid":"a649850d95bfded9","name":"rest_request","source":"a649850d95bfded9.yaml","type":"application/yaml","size":256},{"uid":"20e36040a358f577","name":"rest_response","source":"20e36040a358f577.yaml","type":"application/yaml","size":173}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 4: capmcAPIxnameOnPOSTonComputeNodeStatusCheck - Verify that the target node remained powered on using get_xname_status","time":{"start":1678224332250,"stop":1678224333267,"duration":1017},"status":"passed","steps":[],"attachments":[{"uid":"17a156b5a2eacdd4","name":"stage_yaml","source":"17a156b5a2eacdd4.yaml","type":"application/yaml","size":1083},{"uid":"a61ad7a5d05bbd55","name":"rest_request","source":"a61ad7a5d05bbd55.yaml","type":"application/yaml","size":183},{"uid":"5cafabb330226da0","name":"rest_response","source":"5cafabb330226da0.yaml","type":"application/yaml","size":199}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":5,"attachmentsCount":15,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-capmc-hmth-test"},{"name":"suite","value":"2-disruptive"},{"name":"host","value":"41160d3bdff1"},{"name":"thread","value":"8-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.2-disruptive.test_xname_on.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":3,"broken":0,"skipped":0,"passed":10,"unknown":0,"total":13},"items":[{"uid":"410a37cf283cfbd","status":"passed","time":{"start":1678222042479,"stop":1678222048616,"duration":6137}},{"uid":"d1c6da0afafe30a6","status":"passed","time":{"start":1678218415713,"stop":1678218449437,"duration":33724}},{"uid":"387372bfff0ba887","status":"passed","time":{"start":1676399957042,"stop":1676399990049,"duration":33007}},{"uid":"3d45ae2dca0ee650","status":"passed","time":{"start":1676324760448,"stop":1676324766579,"duration":6131}},{"uid":"69694ee349e59231","status":"passed","time":{"start":1674514807309,"stop":1674514813433,"duration":6124}},{"uid":"4e837b1ea41a0908","status":"passed","time":{"start":1674504922733,"stop":1674504928870,"duration":6137}},{"uid":"7019447d7d75ecdb","status":"passed","time":{"start":1674499489696,"stop":1674499523392,"duration":33696}},{"uid":"ed455f80928807d8","status":"passed","time":{"start":1674257046361,"stop":1674257052500,"duration":6139}},{"uid":"4a6c75b0fe09e495","status":"passed","time":{"start":1674254415787,"stop":1674254448709,"duration":32922}},{"uid":"ee36a3ae1cf29538","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOnPOSTonComputeNodePrep - Power the target node on to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fbcbb3eef70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674080320708,"stop":1674080325756,"duration":5048}},{"uid":"1ca064f9428eca9","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOnPOSTonComputeNodePrep - Power the target node on to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f4927eaaf70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674075035754,"stop":1674075040808,"duration":5054}},{"uid":"44ddfb4a9c84b45d","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOnPOSTonComputeNodePrep - Power the target node on to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f6e85b4af70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674074654685,"stop":1674074659730,"duration":5045}}]},"tags":[]},"source":"700568e6ef51be5c.json","parameterValues":[]}