{"uid":"1f746852dd907376","name":"capmcAPIxnameOffPOSToffComputeNode - Verify xname_off keeps power off for a compute node that is already powered off","fullName":"api.2-disruptive.test_xname_off.tavern#capmcAPIxnameOffPOSToffComputeNode - Verify xname_off keeps power off for a compute node that is already powered off","historyId":"d9f2726aeffb98d202f976e5738a5529","time":{"start":1678226038519,"stop":1678226044651,"duration":6132},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"passed","steps":[{"name":"Stage 0: capmcAPIxnameOffPOSToffComputeNodeTarget - Retrieve a compute node from HSM to be used in later stages","time":{"start":1678226038526,"stop":1678226038562,"duration":36},"status":"passed","steps":[],"attachments":[{"uid":"d068b108bfc402a7","name":"stage_yaml","source":"d068b108bfc402a7.yaml","type":"application/yaml","size":345},{"uid":"8a6464f74ec5f789","name":"rest_request","source":"8a6464f74ec5f789.yaml","type":"application/yaml","size":162},{"uid":"7099a3e2128bbc72","name":"rest_response","source":"7099a3e2128bbc72.yaml","type":"application/yaml","size":5745}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: capmcAPIxnameOffPOSToffComputeNodePrep - Power the target node off to prepare it for the test case","time":{"start":1678226038562,"stop":1678226040586,"duration":2024},"status":"passed","steps":[],"attachments":[{"uid":"efbe2608b419d3cd","name":"stage_yaml","source":"efbe2608b419d3cd.yaml","type":"application/yaml","size":791},{"uid":"20a5db69b6a8f7a9","name":"rest_request","source":"20a5db69b6a8f7a9.yaml","type":"application/yaml","size":256},{"uid":"8315390ea4bb6f29","name":"rest_response","source":"8315390ea4bb6f29.yaml","type":"application/yaml","size":173}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 2: capmcAPIxnameOffPOSToffComputeNodeStatusCheck - Verify that the target node is powered off using get_xname_status","time":{"start":1678226040588,"stop":1678226041606,"duration":1018},"status":"passed","steps":[],"attachments":[{"uid":"a843c2ce1930056a","name":"stage_yaml","source":"a843c2ce1930056a.yaml","type":"application/yaml","size":1083},{"uid":"589728a0b1bd7bbc","name":"rest_request","source":"589728a0b1bd7bbc.yaml","type":"application/yaml","size":183},{"uid":"3755e3bcd2d11f3d","name":"rest_response","source":"3755e3bcd2d11f3d.yaml","type":"application/yaml","size":200}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 3: capmcAPIxnameOffPOSToffComputeNodeActual - Power the target node off using xname_off","time":{"start":1678226041607,"stop":1678226043631,"duration":2024},"status":"passed","steps":[],"attachments":[{"uid":"cb4fead1daac1da8","name":"stage_yaml","source":"cb4fead1daac1da8.yaml","type":"application/yaml","size":779},{"uid":"babbfeb2cc92b5fa","name":"rest_request","source":"babbfeb2cc92b5fa.yaml","type":"application/yaml","size":258},{"uid":"b5542783e1b1b6e1","name":"rest_response","source":"b5542783e1b1b6e1.yaml","type":"application/yaml","size":173}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 4: capmcAPIxnameOffPOSToffComputeNodeStatusCheck - Verify that the target node remained powered off using get_xname_status","time":{"start":1678226043633,"stop":1678226044651,"duration":1018},"status":"passed","steps":[],"attachments":[{"uid":"cb1299a6ac340da6","name":"stage_yaml","source":"cb1299a6ac340da6.yaml","type":"application/yaml","size":1089},{"uid":"341b72c4fc5275f8","name":"rest_request","source":"341b72c4fc5275f8.yaml","type":"application/yaml","size":183},{"uid":"3f5aa12324bbea3a","name":"rest_response","source":"3f5aa12324bbea3a.yaml","type":"application/yaml","size":200}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":5,"attachmentsCount":15,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-capmc-hmth-test"},{"name":"suite","value":"disruptive"},{"name":"host","value":"e5536f8fb70b"},{"name":"thread","value":"8-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.2-disruptive.test_xname_off.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":3,"broken":0,"skipped":0,"passed":11,"unknown":0,"total":14},"items":[{"uid":"9ee5bacfcd9ab953","status":"passed","time":{"start":1678224115766,"stop":1678224121894,"duration":6128}},{"uid":"f05310df7f28b885","status":"passed","time":{"start":1678221830961,"stop":1678221837106,"duration":6145}},{"uid":"bc2c2a65e04c18f9","status":"passed","time":{"start":1678218143809,"stop":1678218177566,"duration":33757}},{"uid":"73f67bcc52a8904e","status":"passed","time":{"start":1676399744895,"stop":1676399751079,"duration":6184}},{"uid":"9bc3adf905f2bf62","status":"passed","time":{"start":1676324519133,"stop":1676324525295,"duration":6162}},{"uid":"fc2821aca57dee87","status":"passed","time":{"start":1674514565564,"stop":1674514571683,"duration":6119}},{"uid":"32dad4e9a4735323","status":"passed","time":{"start":1674504680644,"stop":1674504686780,"duration":6136}},{"uid":"165a9fca59fbaff2","status":"passed","time":{"start":1674499279195,"stop":1674499285327,"duration":6132}},{"uid":"6f173a9e1220d929","status":"passed","time":{"start":1674256803789,"stop":1674256809928,"duration":6139}},{"uid":"f312e662ac9df4be","status":"passed","time":{"start":1674254204244,"stop":1674254210412,"duration":6168}},{"uid":"ee7bf0dd64bf5e3a","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOffPOSToffComputeNodePrep - Power the target node off to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fbcbb3eef70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674080294851,"stop":1674080299898,"duration":5047}},{"uid":"ffeea4edb24fe4a8","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOffPOSToffComputeNodePrep - Power the target node off to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f4927eaaf70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674075009907,"stop":1674075014961,"duration":5054}},{"uid":"b7e074a284a841a9","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOffPOSToffComputeNodePrep - Power the target node off to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f6e85b4af70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674074628981,"stop":1674074634026,"duration":5045}}]},"tags":[]},"source":"1f746852dd907376.json","parameterValues":[]}