{"uid":"410a37cf283cfbd","name":"capmcAPIxnameOnPOSTonComputeNode - Verify xname_on keeps power on for a compute node that is already powered on","fullName":"api.2-disruptive.test_xname_on.tavern#capmcAPIxnameOnPOSTonComputeNode - Verify xname_on keeps power on for a compute node that is already powered on","historyId":"97a360bc5658978b69418312f184c4f0","time":{"start":1678222042479,"stop":1678222048616,"duration":6137},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"passed","steps":[{"name":"Stage 0: capmcAPIxnameOnPOSTonComputeNodeTarget - Retrieve a compute node from HSM to be used in later stages","time":{"start":1678222042487,"stop":1678222042523,"duration":36},"status":"passed","steps":[],"attachments":[{"uid":"6020314793b35067","name":"stage_yaml","source":"6020314793b35067.yaml","type":"application/yaml","size":343},{"uid":"9162101ff0547bb4","name":"rest_request","source":"9162101ff0547bb4.yaml","type":"application/yaml","size":162},{"uid":"ec1816b693bbda6d","name":"rest_response","source":"ec1816b693bbda6d.yaml","type":"application/yaml","size":5773}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: capmcAPIxnameOnPOSTonComputeNodePrep - Power the target node on to prepare it for the test case","time":{"start":1678222042524,"stop":1678222044549,"duration":2025},"status":"passed","steps":[],"attachments":[{"uid":"15286b814aa27853","name":"stage_yaml","source":"15286b814aa27853.yaml","type":"application/yaml","size":786},{"uid":"46c59f19162ce992","name":"rest_request","source":"46c59f19162ce992.yaml","type":"application/yaml","size":254},{"uid":"e694ae93f2003a1","name":"rest_response","source":"e694ae93f2003a1.yaml","type":"application/yaml","size":173}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 2: capmcAPIxnameOnPOSTonComputeNodeStatusCheck - Verify that the target node is powered on using get_xname_status","time":{"start":1678222044550,"stop":1678222045568,"duration":1018},"status":"passed","steps":[],"attachments":[{"uid":"6099a1988bd38d05","name":"stage_yaml","source":"6099a1988bd38d05.yaml","type":"application/yaml","size":1077},{"uid":"6d4ec0536bd08336","name":"rest_request","source":"6d4ec0536bd08336.yaml","type":"application/yaml","size":183},{"uid":"39b93c93b5343383","name":"rest_response","source":"39b93c93b5343383.yaml","type":"application/yaml","size":199}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 3: capmcAPIxnameOnPOSTonComputeNodeActual - Power the target node on using xname_on","time":{"start":1678222045569,"stop":1678222047595,"duration":2026},"status":"passed","steps":[],"attachments":[{"uid":"732a43523e66722e","name":"stage_yaml","source":"732a43523e66722e.yaml","type":"application/yaml","size":773},{"uid":"12d4f7656216eadf","name":"rest_request","source":"12d4f7656216eadf.yaml","type":"application/yaml","size":256},{"uid":"2052ac0adfb5a275","name":"rest_response","source":"2052ac0adfb5a275.yaml","type":"application/yaml","size":173}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 4: capmcAPIxnameOnPOSTonComputeNodeStatusCheck - Verify that the target node remained powered on using get_xname_status","time":{"start":1678222047596,"stop":1678222048615,"duration":1019},"status":"passed","steps":[],"attachments":[{"uid":"a2ccc35bca5352b3","name":"stage_yaml","source":"a2ccc35bca5352b3.yaml","type":"application/yaml","size":1083},{"uid":"2fa0f5fe5099014b","name":"rest_request","source":"2fa0f5fe5099014b.yaml","type":"application/yaml","size":183},{"uid":"f7d0356736c8565d","name":"rest_response","source":"f7d0356736c8565d.yaml","type":"application/yaml","size":199}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":5,"attachmentsCount":15,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-capmc-hmth-test"},{"name":"suite","value":"2-disruptive"},{"name":"host","value":"7e8f40e3eb6a"},{"name":"thread","value":"8-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.2-disruptive.test_xname_on.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":3,"broken":0,"skipped":0,"passed":9,"unknown":0,"total":12},"items":[{"uid":"d1c6da0afafe30a6","status":"passed","time":{"start":1678218415713,"stop":1678218449437,"duration":33724}},{"uid":"387372bfff0ba887","status":"passed","time":{"start":1676399957042,"stop":1676399990049,"duration":33007}},{"uid":"3d45ae2dca0ee650","status":"passed","time":{"start":1676324760448,"stop":1676324766579,"duration":6131}},{"uid":"69694ee349e59231","status":"passed","time":{"start":1674514807309,"stop":1674514813433,"duration":6124}},{"uid":"4e837b1ea41a0908","status":"passed","time":{"start":1674504922733,"stop":1674504928870,"duration":6137}},{"uid":"7019447d7d75ecdb","status":"passed","time":{"start":1674499489696,"stop":1674499523392,"duration":33696}},{"uid":"ed455f80928807d8","status":"passed","time":{"start":1674257046361,"stop":1674257052500,"duration":6139}},{"uid":"4a6c75b0fe09e495","status":"passed","time":{"start":1674254415787,"stop":1674254448709,"duration":32922}},{"uid":"ee36a3ae1cf29538","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOnPOSTonComputeNodePrep - Power the target node on to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fbcbb3eef70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674080320708,"stop":1674080325756,"duration":5048}},{"uid":"1ca064f9428eca9","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOnPOSTonComputeNodePrep - Power the target node on to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f4927eaaf70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674075035754,"stop":1674075040808,"duration":5054}},{"uid":"44ddfb4a9c84b45d","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIxnameOnPOSTonComputeNodePrep - Power the target node on to prepare it for the test case' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f6e85b4af70>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '500' does not exist. Path: '/e' Enum: [0].\n     - Enum 'Error: Failed to send power request to PCS.' does not exist. Path: '/err_msg' Enum: [''].: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674074654685,"stop":1674074659730,"duration":5045}}]},"tags":[]},"source":"410a37cf283cfbd.json","parameterValues":[]}