{"uid":"e6ffbe22c4035b52","name":"capmcAPISetPowerCap","fullName":"api.4-build-pipeline-only.test_set_power_cap.tavern#capmcAPISetPowerCap","historyId":"dd408b17f7b8e55258fcff9f663cd89b","time":{"start":1689615604039,"stop":1689615604240,"duration":201},"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fabe3f66b80>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '22' does not exist. Path: '/e' Enum: [0].\n     - Value '[{'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}, {'nid': 1006, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","statusTrace":"Format variables:\n  capmc_base_url = 'http://cray-capmc:27777'\n  nid0:d = '1006'\n  min0:d = '5036'\n  nid1:d = '20'\n  min1:d = '5036'\n  verify = 'False'\n\nSource test stage (line 184):\n  - name: capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes\n    request:\n      url: \"{capmc_base_url}/capmc/v1/set_power_cap\"\n      json:\n        nids:\n          - nid: !int \"{nid0:d}\"\n            controls:\n              - name: Node Power Limit\n                val: !int \"{min0:d}\"\n          - nid: !int \"{nid1:d}\"\n            controls:\n              - name: Node Power Limit\n                val: !int \"{min1:d}\"\n      method: POST\n      verify: !bool \"{verify}\"\n    response:\n      status_code: 200\n      verify_response_with:\n        function: tavern.testutils.helpers:validate_pykwalify\n        extra_kwargs:\n\n\n\n\n\n\n          schema:\n            type: map\n            mapping:\n              e:\n                type: int\n                required: True\n                enum:\n                  - 0\n              err_msg:\n                type: str\n                required: True\n              nids:\n                type: none\n                required: False\n\n\nFormatted stage:\n  name: capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes\n  request:\n    json:\n      nids:\n      - controls:\n        - name: Node Power Limit\n          val: !int '5036'\n        nid: !int '1006'\n      - controls:\n        - name: Node Power Limit\n          val: !int '5036'\n        nid: !int '20'\n    method: POST\n    url: 'http://cray-capmc:27777/capmc/v1/set_power_cap'\n    verify: !bool 'False'\n  response:\n    status_code: 200\n    verify_response_with:\n      extra_kwargs:\n        schema:\n          mapping:\n            e:\n              enum:\n              - 0\n              required: true\n              type: int\n            err_msg:\n              required: true\n              type: str\n            nids:\n              required: false\n              type: none\n          type: map\n      function: tavern.testutils.helpers:validate_pykwalify\n\nErrors:\nE   tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n    - Error calling validate function '<function validate_pykwalify at 0x7fabe3f66b80>':\n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n            verifier.validate()\n          File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n            raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n        pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n         - Enum '22' does not exist. Path: '/e' Enum: [0].\n         - Value '[{'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}, {'nid': 1006, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n    \n        The above exception was the direct cause of the following exception:\n    \n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n            vf(response)\n          File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n            result = func(response, *args, **kwargs)\n          File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n            verify_generic(to_verify, schema)\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n            raise BadSchemaError() from e\n        tavern.util.exceptions.BadSchemaError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fabe3f66b80>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '22' does not exist. Path: '/e' Enum: [0].\n     - Value '[{'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}, {'nid': 1006, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","statusTrace":"Format variables:\n  capmc_base_url = 'http://cray-capmc:27777'\n  nid0:d = '1006'\n  min0:d = '5036'\n  nid1:d = '20'\n  min1:d = '5036'\n  verify = 'False'\n\nSource test stage (line 184):\n  - name: capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes\n    request:\n      url: \"{capmc_base_url}/capmc/v1/set_power_cap\"\n      json:\n        nids:\n          - nid: !int \"{nid0:d}\"\n            controls:\n              - name: Node Power Limit\n                val: !int \"{min0:d}\"\n          - nid: !int \"{nid1:d}\"\n            controls:\n              - name: Node Power Limit\n                val: !int \"{min1:d}\"\n      method: POST\n      verify: !bool \"{verify}\"\n    response:\n      status_code: 200\n      verify_response_with:\n        function: tavern.testutils.helpers:validate_pykwalify\n        extra_kwargs:\n\n\n\n\n\n\n          schema:\n            type: map\n            mapping:\n              e:\n                type: int\n                required: True\n                enum:\n                  - 0\n              err_msg:\n                type: str\n                required: True\n              nids:\n                type: none\n                required: False\n\n\nFormatted stage:\n  name: capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes\n  request:\n    json:\n      nids:\n      - controls:\n        - name: Node Power Limit\n          val: !int '5036'\n        nid: !int '1006'\n      - controls:\n        - name: Node Power Limit\n          val: !int '5036'\n        nid: !int '20'\n    method: POST\n    url: 'http://cray-capmc:27777/capmc/v1/set_power_cap'\n    verify: !bool 'False'\n  response:\n    status_code: 200\n    verify_response_with:\n      extra_kwargs:\n        schema:\n          mapping:\n            e:\n              enum:\n              - 0\n              required: true\n              type: int\n            err_msg:\n              required: true\n              type: str\n            nids:\n              required: false\n              type: none\n          type: map\n      function: tavern.testutils.helpers:validate_pykwalify\n\nErrors:\nE   tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n    - Error calling validate function '<function validate_pykwalify at 0x7fabe3f66b80>':\n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n            verifier.validate()\n          File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n            raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n        pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n         - Enum '22' does not exist. Path: '/e' Enum: [0].\n         - Value '[{'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}, {'nid': 1006, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n    \n        The above exception was the direct cause of the following exception:\n    \n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n            vf(response)\n          File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n            result = func(response, *args, **kwargs)\n          File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n            verify_generic(to_verify, schema)\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n            raise BadSchemaError() from e\n        tavern.util.exceptions.BadSchemaError","steps":[{"name":"Stage 0: capmcAPISetPowerCap - setup1 - Get HSM Nodes","time":{"start":1689615604050,"stop":1689615604093,"duration":43},"status":"passed","steps":[],"attachments":[{"uid":"e0df92a2305bf9dc","name":"stage_yaml","source":"e0df92a2305bf9dc.yaml","type":"application/yaml","size":457},{"uid":"bb2700e19f7632ab","name":"rest_request","source":"bb2700e19f7632ab.yaml","type":"application/yaml","size":149},{"uid":"77b1592a5dcd550","name":"rest_response","source":"77b1592a5dcd550.yaml","type":"application/yaml","size":5775}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: capmcAPISetPowerCap - setup2 - get_power_cap_capabilities","time":{"start":1689615604093,"stop":1689615604158,"duration":65},"status":"passed","steps":[],"attachments":[{"uid":"84b77478606e567d","name":"stage_yaml","source":"84b77478606e567d.yaml","type":"application/yaml","size":472},{"uid":"2444bb36ecc29f75","name":"rest_request","source":"2444bb36ecc29f75.yaml","type":"application/yaml","size":171},{"uid":"9e9a1e2fbd7e1441","name":"rest_response","source":"9e9a1e2fbd7e1441.yaml","type":"application/yaml","size":980}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 2: capmcAPISetPowerCap - setup3 - Set HSM Node 0 to Off","time":{"start":1689615604159,"stop":1689615604170,"duration":11},"status":"passed","steps":[],"attachments":[{"uid":"feb7c1d3a0cf17d3","name":"stage_yaml","source":"feb7c1d3a0cf17d3.yaml","type":"application/yaml","size":247},{"uid":"778fe630ece0c0f7","name":"rest_request","source":"778fe630ece0c0f7.yaml","type":"application/yaml","size":173},{"uid":"f98758b92fd6e676","name":"rest_response","source":"f98758b92fd6e676.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 3: capmcAPISetPowerCap - setup4 - Set HSM Node 1 to Off","time":{"start":1689615604171,"stop":1689615604180,"duration":9},"status":"passed","steps":[],"attachments":[{"uid":"c449e5693e8b927","name":"stage_yaml","source":"c449e5693e8b927.yaml","type":"application/yaml","size":247},{"uid":"b027b81e3528fea1","name":"rest_request","source":"b027b81e3528fea1.yaml","type":"application/yaml","size":173},{"uid":"bd8190d39e917b34","name":"rest_response","source":"bd8190d39e917b34.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 4: capmcAPISetPowerCap - test1 - POST set_power_cap for powered off node - failure test","time":{"start":1689615604181,"stop":1689615604198,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"3d2bef29ff7e6a18","name":"stage_yaml","source":"3d2bef29ff7e6a18.yaml","type":"application/yaml","size":1395},{"uid":"10ffa774e2451d0","name":"rest_request","source":"10ffa774e2451d0.yaml","type":"application/yaml","size":214},{"uid":"8b89d2f694e65ba8","name":"rest_response","source":"8b89d2f694e65ba8.yaml","type":"application/yaml","size":287}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 5: capmcAPISetPowerCap - setup5 - Set HSM Node 0 to Ready","time":{"start":1689615604199,"stop":1689615604208,"duration":9},"status":"passed","steps":[],"attachments":[{"uid":"b66bc3b59e42211f","name":"stage_yaml","source":"b66bc3b59e42211f.yaml","type":"application/yaml","size":251},{"uid":"cca6a4e70c14a96a","name":"rest_request","source":"cca6a4e70c14a96a.yaml","type":"application/yaml","size":173},{"uid":"70e439609e5c7c6f","name":"rest_response","source":"70e439609e5c7c6f.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 6: capmcAPISetPowerCap - setup6 - Set HSM Node 1 to Ready","time":{"start":1689615604209,"stop":1689615604219,"duration":10},"status":"passed","steps":[],"attachments":[{"uid":"ead85cffda280900","name":"stage_yaml","source":"ead85cffda280900.yaml","type":"application/yaml","size":251},{"uid":"c4f1f0d28cd17d38","name":"rest_request","source":"c4f1f0d28cd17d38.yaml","type":"application/yaml","size":173},{"uid":"8a4c6b48c6b75fc7","name":"rest_response","source":"8a4c6b48c6b75fc7.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 7: capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes","time":{"start":1689615604219,"stop":1689615604239,"duration":20},"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fabe3f66b80>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '22' does not exist. Path: '/e' Enum: [0].\n     - Value '[{'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}, {'nid': 1006, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError\n\n","statusTrace":"  File \"/usr/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/usr/lib/python3.9/site-packages/tavern/util/retry.py\", line 31, in wrapped\n    res = fn(*args, **kwargs)\n  File \"/usr/lib/python3.9/site-packages/tavern/core.py\", line 270, in run_stage\n    saved = v.verify(response)\n  File \"/usr/lib/python3.9/site-packages/tavern/_plugins/rest/response.py\", line 201, in verify\n    raise exceptions.TestFailError(\n","steps":[],"attachments":[{"uid":"845eae76158954e7","name":"stage_yaml","source":"845eae76158954e7.yaml","type":"application/yaml","size":903},{"uid":"de6baaa1843886c1","name":"rest_request","source":"de6baaa1843886c1.yaml","type":"application/yaml","size":286},{"uid":"e20481d94c6e4557","name":"rest_response","source":"e20481d94c6e4557.yaml","type":"application/yaml","size":394}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[{"uid":"7911ac00278cab94","name":"error_output","source":"7911ac00278cab94.attach","type":"text/plain","size":3773},{"uid":"53cc03a5b5d31327","name":"log","source":"53cc03a5b5d31327.txt","type":"text/plain","size":4427}],"parameters":[],"stepsCount":8,"attachmentsCount":26,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-capmc-hmth-test"},{"name":"suite","value":"build-pipeline-only"},{"name":"host","value":"ba72cc84991a"},{"name":"thread","value":"8-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.4-build-pipeline-only.test_set_power_cap.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"e6ffbe22c4035b52.json","parameterValues":[]}